@startuml
node "PLC"{
   folder "Robot Request" {
       [coordinate]
       [Command Num]
   }
   folder "Robot Response" {
       [Robot Data]
   }
   folder "Vision Request" {
       [Order]
   }
   folder "Vision Response" {
        [Vision Data]
   }
   folder "Tool Request" {
        [Mechanism Position]
        [Exec Request]
   }
   folder "Tool Exec" {
        [Exec]
   }
}


node "Flexible Production System" {
    node "FCP-Components" {
        node "FCP-R" {
            node "RobotAPI" {
                [Dobot]
                [Yamaha]
                [RoboDK]
            }
        }
        node "FCP-V" {
            node "VisionAPI" {
                [VisionMasterAPI]
                [FacileaAPI]
                [VASTAPI]
            }
        }
        node "FCP-T" {
                [I/O]
                [Pulse]
                [Command]
        }
    }
    node "FCP-Communication" {
        [MCProtcol]
        [Fins]
        [OPC UA]
    }


}
'node "r" {
'    [Robot]
'    [Simulator]
'    [Tool]
'}
'node "v" {
'    [Vision]
'}

'大ノード位置調整
"PLC" -[hidden]- "Flexible Production System"
'"Flexible Production System" -[hidden]- "r"
'"Flexible Production System" -[hidden]- "v"

"FCP-Communication"- "PLC":MCProtocol
"FCP-Communication" - "FCP-Components":Mosquitto
"FCP-Components" -- "FCP-R": Daemon
"FCP-Components" -- "FCP-V": Daemon

'位置調整（PLC内)
"Robot Request" -[hidden] "Robot Response"
"Robot Response" -[hidden] "Vision Request"
"Vision Request" -[hidden] "Vision Response"
"Tool Request" -[hidden] "Tool Exec"
'"Tool Exec" -[hidden] "Robot Request"
"Vision Response" -[hidden] [I/O]

''位置調整
'"Flexible Production System" -[hidden]- [Vision]
'[Vision] -[hidden] [Simulator]
'[Simulator] -[hidden] [Robot]
'[Robot] -[hidden] [Tool]
'"Flexible Production System" -[hidden]- [Robot]
'"Flexible Production System" -[hidden]- [Simulator]
'"Flexible Production System" -[hidden]- [Tool]
'"FCP-V" -[hidden] "FCP-R"


'"RobotAPI" -- "r"
'"ToolAPI" -- "Tool Exec"
'"Tool Exec" -- [Tool]
'"RobotAPI" -- [Simulator]
'"ToolAPI" -- [Simulator]
'[Tool Controller] -- [Tool]
@enduml