P1:
  name: A1
  x_pos: 250.583
  y_pos: 80.325
  z_pos: 57.623
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P2:
  name: B1
  x_pos: 279.923
  y_pos: 72.105
  z_pos: 57.623
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P3:
  name: C1
  x_pos: 254.528
  y_pos: 119.865
  z_pos: 57.623
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P4:
  name: D1
  x_pos: 296.925
  y_pos: 106.605
  z_pos: 57.623
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P5:
  name: A2
  x_pos: 250.583
  y_pos: 80.325
  z_pos: 57.623
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P6:
  name: B2
  x_pos: 279.923
  y_pos: 72.105
  z_pos: 57.623
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P7:
  name: C2
  x_pos: 254.528
  y_pos: 119.865
  z_pos: 57.623
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P8:
  name: D2
  x_pos: 296.925
  y_pos: 106.605
  z_pos: 57.623
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P9:
  name: Pick_TOP
  x_pos: 250.583
  y_pos: 80.325
  z_pos: 19
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P10:
  name: Pick_MID
  x_pos: 250.583
  y_pos: 80.325
  z_pos: 35
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P11:
  name: Pick_BTM
  x_pos: 250.583
  y_pos: 80.325
  z_pos: 58.463
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P12:
  name: Place_TOP
  x_pos: 269.948
  y_pos: 218.453
  z_pos: 19
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P13:
  name: Place_MID
  x_pos: 269.948
  y_pos: 218.453
  z_pos: 35
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
P14:
  name: Place_BTM
  x_pos: 269.948
  y_pos: 218.453
  z_pos: 58
  rz_pos: 0
  ry_pos: 0
  rx_pos: 0
  vel: 10
  acc: 0.1
  dec: 0.1
