# config.yaml
P1:
  name: TOP
  x: 20.0
  y: 20.0
  z: 30.0
  rz: 3
  ry: 2
  rx: 1
  vel: 10.0
  acc: 0.1
  dec: 0.2

P2:
  name: MID
  x: 200.0
  y: 200.0
  z: 300.0
  rz: 3
  ry: 2
  rx: 1
  vel: 10.0
  acc: 0.1
  dec: 0.2

P3:
  name: BTM
  x: 200.0
  y: 200.0
  z: 300.0
  rz: 3
  ry: 2
  rx: 1
  vel: 10.0
  acc: 0.1
  dec: 0.2

P4:
  name: HOME
  x: 200.0
  y: 200.0
  z: 300.0
  rz: 3
  ry: 2
  rx: 1
  vel: 10.0
  acc: 0.1
  dec: 0.2