@startuml

PLC -> 卓ロボ: プログラム起動
activate PLC
activate 卓ロボ
卓ロボ -> 卓ロボ: プログラムの自動運転開始
卓ロボ --> PLC: 起動完了
deactivate PLC
deactivate 卓ロボ

PLC -> 卓ロボ: ティーチングデータ書込み
activate PLC
activate 卓ロボ
卓ロボ -> 卓ロボ: コントローラのポジションデータに\nティーチングデータ書き込み
卓ロボ --> PLC: 書き込み完了
deactivate PLC
deactivate 卓ロボ

PLC -> 卓ロボ: フラグON
activate PLC
activate 卓ロボ
卓ロボ -> 卓ロボ: 多点連結動作
卓ロボ --> PLC: ON完了
deactivate PLC
deactivate 卓ロボ


@enduml