@startuml
hide footbox
title blockly.py画面
group フロー生成
    [-> blockly.py : ティーチングデータ読込み\n(.json形式)
    blockly.py -> blockly.py: move引数設定\n・ポイント番号(プルダウン形式)
end
group フロー再生
    blockly.py -> kit_com.py: move命令\n(UDP経由)
    activate kit_com.py
        activate blockly.py
            kit_com.py -> main.py: move命令\n(import経由)
            activate main.py
                main.py --> kit_com.py: move結果\n(import経由)
            deactivate main.py
            kit_com.py --> blockly.py: move結果\n(UDP経由)
        deactivate blockly.py
    deactivate kit_com.py
end
@enduml