@startuml{plantuml_usecase_subject.png}
left to right direction

actor :ラダー未経験者: as beginner
actor :ラダー経験者: as expert

rectangle "RasPi"{
    beginner --> (Blocklyでプログラムを作成する)
    beginner --> (Pythonプログラムを実行する)
    expert --> (ニーモニックを吐き出す)
}

rectangle "PLC"{
    expert --> (Blocklyでプログラムを作成する)
    expert --> (Pythonプログラムを実行する)
    expert --> (ニーモニックを読み込む)
    expert --> (ラダープログラムを編集する)
    expert --> (ラダープログラムを実行する)
}

rectangle "ロボット" {
    Pythonプログラムを実行する --> (ロボットが動作する)
    ラダープログラムを実行する --> (ロボットが動作する)
}
@enduml