@startuml
title TCP通信フロー(クライアント)

start

fork
    :オープン開始;
    while (オープン処理OK?) is (no)
        :クローズ処理;
        if (クローズ処理OK?) then (yes)
            if (オープン所定\n回数以上?) then (no)
            else (yes)
                #Pink:エラー出力;
                kill
            endif
        else (no)
            #Pink:エラー出力;
            kill
        endif
    endwhile
fork again
    while (動作開始命令有?) is (no)
    endwhile (yes)

end fork
    repeat
        :データ送信処理;
        if (データ送信OK?) then (yes)
            :データ受信処理;
            if (データ受信OK?) then (yes)
            else (no)
                :クローズ処理;
                #Pink:エラー出力;
                kill
            endif
        else (no)
            :クローズ処理;
            #Pink:エラー出力;
            kill
        endif
    repeat while (動作開始命令有?) is (yes)
stop

@enduml