@startuml
hide footbox
title Teching画面
group ティーチング作業
    loop ロボット所定位置移動完了まで
        teaching.py -> kit_com.py: move命令\n(UDP経由)
        activate kit_com.py
            activate teaching.py
                kit_com.py -> main.py: move命令\n(import経由)
                activate main.py
                    main.py --> kit_com.py: move結果\n(import経由)
                deactivate main.py
                kit_com.py --> teaching.py: move結果\n(UDP経由)
            deactivate teaching.py
        deactivate kit_com.py
    end
    teaching.py -> teaching.py: 現在位置取り込み
    teaching.py -> teaching.py: 座標更新
end
opt 画面遷移するなら
    teaching.py -> teaching.py: ティーチングデータ生成\n(.json形式)
end 
@enduml